# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Storm, Earth & Lava
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Guides for Elemental Shamans of World of Warcraft
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
patreon_name: stormearthlava
discord_servername: Storm, Earth & Lava
discord_invite: https://discord.gg/VA7wXVx
twitter_username: StormEarthLava
github_username:  stormearthandlava
timezone: Australia/Sydney

# Hide posts that are scheduled for the future. Do not set to true unless you are VERY sure you know what you're doing:
future: false

# Build settings
markdown: kramdown
# standard
# https://github.com/jekyll/minima
theme: minima
show_download: false
show_excerpts: true # show excerpt of posts

plugins:
  #- jekyll-feed
  - jekyll-paginate


# paginate value, how many posts shall be shown per page? (especially on the front page)
paginate: 6

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Page defaults
defaults:
  -
    scope:
      type: "pages"
    values:
      toc: true
  -
    scope:
      type: "posts"
    values:
      toc: false
